routes:
  /:
    data: page.home
    template: home

  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
    
  /about/team/:
    template: team
    data: page.team

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
  /newsletter/:
    permalink: /{slug}/
    template: index
    filter: visibility:-public